--mostra os nomes dos funcionários que trabalham numa dada loja

.mode	columns
.headers	on
.nullvalue	NULL

CREATE VIEW FUNCIONARIOSBASICINFO AS
SELECT FUNCIONARIO.Pessoa_ID, PESSOA.Nome, FUNCIONARIO.Ordenado
FROM FUNCIONARIO, PESSOA
WHERE PESSOA.ID=FUNCIONARIO.Pessoa_ID;

SELECT DISTINCT FUNCIONARIOSBASICINFO.Nome, FUNCIONARIOSBASICINFO.Ordenado
FROM FUNCIONARIOSBASICINFO, TRABALHAEM
WHERE TRABALHAEM.Loja_Endereço="Rua Henrique de Sousa Reis, 4200-003" AND TRABALHAEM.Funcionario_ID=FUNCIONARIOSBASICINFO.Pessoa_ID;

DROP VIEW FUNCIONARIOSBASICINFO;
