CREATE TRIGGER VERIFICA_PESSOA
BEFORE UPDATE OF NIB ON PESSOA
FOR EACH ROW
WHEN EXISTS (SELECT *
             FROM PESSOA
             WHERE NIB = New.NIB)
BEGIN
  SELECT RAISE (ROLLBACK, 'NIB ja existe.');
END;
