SELECT * FROM PRODUTO;
SELECT * FROM DESCONTO;
SELECT * FROM DISTRIBUI;
SELECT * FROM VENDAS;

DELETE FROM TIPOPRODUTO
WHERE  ID=2;

SELECT * FROM PRODUTO;
SELECT * FROM DESCONTO;
SELECT * FROM DISTRIBUI;
SELECT * FROM VENDAS;
