.mode columns
.headers on

DROP TABLE IF EXISTS PESSOA;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS PRODUTO;
DROP TABLE IF EXISTS COMPRA;
DROP TABLE IF EXISTS GESTOR;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS LOJA;
DROP TABLE IF EXISTS PRODUTO;
DROP TABLE IF EXISTS TIPOPRODUTO;

CREATE TABLE PESSOA (
  ID INTEGER PRIMARY KEY,
  Nome TEXT DEFAULT "none", -- verificar se pode ser NULL ou não
  Idade INTEGER DEFAULT 18 CHECK(Idade > 17), --não podemos ter clientes menores de idade?
  Morada TEXT(100) DEFAULT "none",
  Genero TEXT(1) DEFAULT "F" CHECK( Genero = "F" or Genero = "M"),
  UNIQUE (Nome, Morada)
);

CREATE TABLE CLIENTE (
  NrCliente INTEGER PRIMARY KEY,
  Pessoa_ID INTEGER REFERENCES PESSOA,
  NIB INTEGER UNIQUE,
  UNIQUE(Pessoa_ID, NIB),
  UNIQUE(Pessoa_ID, NrCliente)
);

CREATE TABLE GESTOR (
  ID INTEGER PRIMARY KEY,
  Pessoa_ID INTEGER REFERENCES PESSOA,
  NIB INTEGER UNIQUE,
  Ordenado REAL CHECK (Ordenado > 0),
  Contacto TEXT(14) UNIQUE,
  Email TEXT(40) UNIQUE,
  DataInicio DATE NOT NULL,
  DataFim DATE NOT NULL,
  UNIQUE(Pessoa_ID, NIB),
  UNIQUE(Pessoa_ID, ID)
);

CREATE TABLE FUNCIONARIO (
  ID INTEGER PRIMARY KEY,
  Pessoa_ID INTEGER NOT NULL REFERENCES PESSOA,
  NIB INTEGER UNIQUE,
  RegimeTrabalho TEXT(50) NOT NULL,
  DuracaoContrato INTEGER NOT NULL CHECK (DuracaoContrato > 0),
  DataInicio DATE NOT NULL,
  DataFim DATE NOT NULL CHECK (DataFim > DataInicio),
  UNIQUE(Pessoa_ID, NIB),
  UNIQUE(Pessoa_ID, ID)
);

CREATE TABLE LOJA (
  Endereço TEXT(70) PRIMARY KEY,
  Telefone TEXT(14) NOT NULL,
  Horario TEXT(20) NOT NULL,
  Gestor_ID INTEGER NOT NULL REFERENCES GESTOR,
  UNIQUE(Endereço, Gestor_ID),
  UNIQUE(Endereço, Telefone)
);

CREATE TABLE PRODUTO (
  ID INTEGER,
  QuantidadeProduto INTEGER DEFAULT 0 CHECK (QuantidadeProduto > -1),
  Nome TEXT(70) NOT NULL,
  TipoProduto_ID INTEGER NOT NULL REFERENCES TIPOPRODUTO,
  PRIMARY KEY(ID, Nome)
);

CREATE TABLE TIPOPRODUTO (
  ID INTEGER PRIMARY KEY,
  Nome TEXT NOT NULL,
  Preco REAL NOT NULL,
  BarCode TEXT(50) NOT NULL,
  DataValidade DATE NOT NULL,
  Fornecedor_ID NOT NULL REFERENCES FORNECEDOR
);

CREATE TABLE DESCONTO (
  ID INTEGER PRIMARY KEY,
  Percentage REAL NOT NULL CHECK(Percentage > 0 and Percentage < 100),
  DataInicio DATE NOT NULL,
  DataFim DATE NOT NULL CHECK (DataFim > DataInicio),
  Loja_Endereço TEXT (70) REFERENCES LOJA,
  TipoProduto_ID INTEGER REFERENCES TIPOPRODUTO
)
